apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  namespace: istio-http-example
spec:
  hosts:
    - "backend"
  http:
  - route:
    - destination:
        host: backend
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
  namespace: istio-http-example
spec:
  host: backend
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v0
    labels:
      version: "0"
  - name: v1
    labels:
      version: "1"

