apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: playground
  labels:
    app: backend
spec:
  ports:
  - port: 9090
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend
